# argocd app sync testapp-dev01
# argocd app get testapp-dev01
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-dev01
  namespace: argocd
spec:
  project: default
  source:
    # Kustomize repo
    repoURL: 'https://github.com/REPO_USERNAME/REPO_NAME.git'
    targetRevision: HEAD
    path: overlays/production
  destination:
    server: 'https://kubernetes.default.svc'
    # app namespace
    namespace: dev01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
